Feature/net
satviz/satviz pull request #24
Opened 2022-02-15 12:26 UTC by LuWae

Hier ist die satviz-Kommunikation zwischen Produzent und Konsument implementiert.

Die Kommunikation zwischen Produzent und Konsument wird als Folge von NetworkMessages modelliert. Ein Receiver wandelt einen Byte-Strom mithilfe des serial-Moduls in NetworkMessages um. Client- und ServerConnectionManager verwalten die Kommunikation über non-blocking Sockets. Darauf aufbauend stellen ProducerConnection und ConsumerConnection eine Fassade dar, die eine vereinfachte Schnittstelle anbieten.

Ein einzelner Konsument kann gleichzeitig mehrere Produzenten verwalten. Die Identifikation funktioniert mit ProducerIDs, die gleichzeitig Informationen über die jeweiligen Produzenten liefern.
Die Kommunkiation läuft über Observer/Listener. Als Schnittstelle gibt es dafür ProducerConnectionListener und ConsumerConnectionListener.

Die Schnittstellen von ProducerConnection/ConsumerConnection und den entsprechenden Listener haben sich gegenüber dem Entwurf ein wenig verändert, haben aber die gleiche Funktion.

Hier sind leider auch noch mal einige serial-Klassen aufgelistet, weil ich die manuell kopiert habe. Daran sollte sich nichts verändert haben.

2022-02-15 20:23 UTC, JohnnyJayJay requested changes

2022-02-15 20:23 UTC, JohnnyJayJay commented on satviz-network/src/main/java/edu/kit/satviz/network/ConsumerConnection.java
> +  public ConsumerConnection(int port) {
Es scheint derzeit noch nicht möglich zu sein, einen freien Port zugewiesen zu bekommen, so wie ich das sehe. Das sollte in irgendeiner Form ermöglicht werden.

2022-02-15 20:23 UTC, JohnnyJayJay commented on satviz-network/src/main/java/edu/kit/satviz/network/ConsumerConnectionListener.java
>  public interface ConsumerConnectionListener {
Die Methoden hier sollten alle `default` Implementationen haben, die nichts tun.

2022-02-15 20:23 UTC, JohnnyJayJay commented on satviz-network/src/main/java/edu/kit/satviz/network/ProducerConnectionListener.java
>  public interface ProducerConnectionListener {
Auch hier sollten die Methoden `default` stubs haben

2022-02-15 21:38 UTC, LuWae commented on satviz-network/src/main/java/edu/kit/satviz/network/ConsumerConnection.java
> +  public ConsumerConnection(int port) {
Port 0 für automatische Zuweisung

2022-02-16 13:05 UTC, JohnnyJayJay approved these changes

2022-02-16 13:06 UTC, merged