Finished data-classes in the satviz-sat module
satviz/satviz pull request #5
Opened 2022-01-20 14:19 UTC by quorty

Alle entworfenen Klassen für das Sat-Modul wurden implementiert mit der zum Entwurf verschiedenen Schnittstelle der SatAssignment Klasse. Im letzten Commit wurde die Implementierung der Klasse obendrauf zu VariableState-array verändert, anstelle des vorher existierenden byte-arrays, der jeweils 4 Variablen per Eintrag gespeichert hatte.

2022-01-20 15:05 UTC, JohnnyJayJay requested changes
Habe ein paar Kommentare zu Formalitäten und bei `SatAssignment` auch ein paar inhaltliche Vorschläge dagelassen.

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/ClauseUpdate.java
> + * This record is adds additional information to the Clause record.<br>
~~is~~ adds

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> + * This class represents a finished solution for a SAT-instance.
Ein `SatAssignment` ist keine Lösung, sondern erstmal nur eine *Wahrheitsbelegung* der Variablen einer SAT-Instanz.

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +    }
Der Sinn dieses `if`s ist mir nicht ganz klar. Warum speichern wir einen int zu viel bei `varCount > 0`? Wir können es einfach wie ein 0-indiziertes array behandeln (intern) und nach außen eine 1-indizierte API anbieten (s.u.).\
Das Attribut `varCount` können wir uns auch sparen; Das ist dann einfach `satAssignment.length`.
```suggestion
    this.satAssignment = new VariableState[varCount];
```

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +      return;
Besser eine `IllegalArgumentException` werfen statt einfach nichts zu tun.

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +    this.satAssignment[variable] = state;
Siehe Kommentar zum Konstruktor.
```suggestion
    this.satAssignment[variable - 1] = state;
```

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +    return this.satAssignment[variable];
Siehe Kommentar zum Konstruktor.
```suggestion
    return this.satAssignment[variable - 1];
```

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +      return VariableState.DONTCARE;
Auch hier würde ich eher eine `IllegalArgumentException` werfen.

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +   * <code>0</code> <i>is returned.</i>
Der einzige invalid state ist `RESERVED` und dieser sollte hier dann wieder eine `IllegalArgumentException` hervorrufen.

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +    public final byte val;
Wird dieser ganze `byte`-Kram hier noch benötigt? Ich würde das dann auch lieber zum Serialiser schieben, wie den Rest, den du ja schon entfernt hast.

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
>  public class SatAssignment {
SatAssignment ist ein guter Kandidat um `equals`, `hashCode` und `toString` zu implementieren.

2022-01-20 15:05 UTC, JohnnyJayJay commented on satviz-sat/src/test/java/edu/kit/satviz/sat/SatAssignmentTest.java
> +  private void recursive_test(int depth, int varCount) {
Bei `@Test`-Methoden sind `_` [zur Separierung logischer Komponenten](https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names) ok, bei Hilfsmethoden würde ich an den normalen Konventionen bleiben.
```suggestion
  private void recursiveTest(int depth, int varCount) {
```

2022-01-20 15:22 UTC, LuWae commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +    public final byte val;
Ja hast recht, das passt da nicht mehr hin

2022-01-20 16:54 UTC, quorty commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> + * This class represents a finished solution for a SAT-instance.
Nun steht dort: 

> This class holds a truth assignment for the variables of a SAT-instance.

2022-01-20 16:56 UTC, quorty commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +    }
Der array wird nun intern wie ein 0-indiziertes array behandelt und es werden nun IllegalArgumentExceptions ausgegeben im falle von ungültigen Parametern!

2022-01-20 16:57 UTC, quorty commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +    this.satAssignment[variable] = state;
An allen Stellen wurde das nun entsprechend des 0-indizierten Arrays angepasst.

2022-01-20 16:58 UTC, quorty commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
> +    public final byte val;
Wurde vollständig entfernt.

2022-01-20 16:58 UTC, quorty commented on satviz-sat/src/main/java/edu/kit/satviz/sat/SatAssignment.java
>  public class SatAssignment {
Wurde hinzugefügt.

2022-01-20 16:59 UTC, quorty commented on satviz-sat/src/test/java/edu/kit/satviz/sat/SatAssignmentTest.java
> +  private void recursive_test(int depth, int varCount) {
Das wurde angepasst, aber denkst du Namen wie `set_invalidParameters_test()` sind in Ordnung?

2022-01-20 17:03 UTC, JohnnyJayJay commented on satviz-sat/src/test/java/edu/kit/satviz/sat/SatAssignmentTest.java
> +  private void recursive_test(int depth, int varCount) {
Ja, das folgt der Idee von `<getesteteMethode>_<testCase>`

2022-01-21 12:17 UTC, JohnnyJayJay requested changes
Gut! Nur noch eine Sache: Gib den `IllegalArgumentException`s noch eine `message` mit, die kurz sagt, was falsch ist.

2022-01-21 15:16 UTC, merged