Feature/vis theming
satviz/satviz pull request #55
Opened 2022-03-14 12:30 UTC by tomolt

Die Farben der Darstellung (und die Größe der Knoten auf dem Bildschirm) können jetzt von Java-Seite aus angepasst werden.
Die Darstellung reagiert auch darauf, wenn während der Visualisierung die Heatmap-Farben angepasst werden.

Was noch fehlt ist das Übernehmen der Farben aus der Config.
Dazu sollte evtl. die Config nochmal angepasst werden. Aktuell sind die Farben dort als `int` abgespeichert,
wir brauchen aber eigentlich `float[3]` überall.

2022-03-14 13:00 UTC, luwae approved these changes

2022-03-19 11:10 UTC, Tim-17 requested changes
Die Umbenennung "from" = "cold" und "to" = "hot" wurde vertauscht. Ich hab einige Stellen angemerkt; da gibt es aber sicher noch ein paar unmarkierte Stellen, bei denen das noch aktualisiert werden muss...

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/cli/HeatmapColorsType.java
> +import edu.kit.satviz.consumer.gui.GuiUtils;
Den Import scheinst du gar nicht zu verwenden

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/HeatmapColors.java
> +   * The default hot color.
from = cold

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/HeatmapColors.java
> +   * The default cold color.
to = hot

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/HeatmapColors.java
> +    return hotColor == colors.hotColor && coldColor == colors.coldColor;
Da wir hier keine primitiven Datentypen mehr verwenden, sollte hier "equals" verwendet werden.
```suggestion
    return coldColor.equals(colors.coldColor) && hotColor.equals(colors.hotColor);
```

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/config/GeneralConfigController.java
> +    coldColorColorPicker.setValue(HeatmapColors.DEFAULT_HOT_COLOR);
Siehe vorheriger Kommentar
```suggestion
    coldColorColorPicker.setValue(HeatmapColors.DEFAULT_COLD_COLOR);
```

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/config/GeneralConfigController.java
> +    hotColorColorPicker.setValue(HeatmapColors.DEFAULT_COLD_COLOR);
Siehe vorheriger Kommentar
```suggestion
    hotColorColorPicker.setValue(HeatmapColors.DEFAULT_HOT_COLOR);
```

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/config/GeneralConfigController.java
> +      coldColorColorPicker.setValue(colors.getHotColor());
same here
```suggestion
      coldColorColorPicker.setValue(colors.getColdColor());
```

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/config/GeneralConfigController.java
> +      hotColorColorPicker.setValue(colors.getColdColor());
and here
```suggestion
      hotColorColorPicker.setValue(colors.getHotColor());
```

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/config/GeneralConfigController.java
> +    colors.setHotColor(coldColorColorPicker.getValue());
again
```suggestion
    colors.setHotColor(hotColorColorPicker.getValue());
```

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/config/GeneralConfigController.java
> +    colors.setColdColor(hotColorColorPicker.getValue());
and again
```suggestion
    colors.setColdColor(coldColorColorPicker.getValue());
```

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/visualization/VisualizationController.java
> +    coldColorColorPicker.setValue(colors.getHotColor());
again
```suggestion
    coldColorColorPicker.setValue(colors.getColdColor());
```

2022-03-19 11:10 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/visualization/VisualizationController.java
> +    hotColorColorPicker.setValue(colors.getColdColor());
and again
```suggestion
    hotColorColorPicker.setValue(colors.getHotColor());
```

2022-03-19 11:42 UTC, Tim-17 requested changes
Nochmal Änderungsvorschläge für das Color-Parsing von der CLI aus.

2022-03-19 11:42 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/cli/HeatmapColorsType.java
> +    heatmapColors.setHotColor(intToColor(Integer.parseInt(stringArray[0].substring(1))));
Hier auch das Problem mit from = cold / to = hot. 
Zudem kann man einfach die API von Color verwenden, um das direkt vom String aus zu parsen. Ich weiß nicht, ob die Verwendung so zu 100% stimmt, aber das ist zumindest der Ansatz.
```suggestion
    heatmapColors.setColdColor(Color.web(stringArray[0]));
```

2022-03-19 11:42 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/cli/HeatmapColorsType.java
> +    heatmapColors.setColdColor(intToColor(Integer.parseInt(stringArray[1].substring(1))));
Gleiches wie oben drüber
```suggestion
    heatmapColors.setHotColor(Color.web(stringArray[1]));
```

2022-03-19 11:42 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/cli/HeatmapColorsType.java
> +  private static Color intToColor(int color) {
Die Methode wird mit den Änderungen von oben überflüssig.

2022-03-19 16:03 UTC, quorty commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/HeatmapColors.java
> +   * The default hot color.
komisch, ich hatte das schon angepasst

2022-03-19 16:04 UTC, quorty commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/HeatmapColors.java
> +   * The default hot color.
achso danke verstehe

2022-03-22 19:01 UTC, Tim-17 requested changes
Paar Kleinigkeiten, sonst sieht's gut aus

2022-03-22 19:01 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/HeatmapColors.java
> +    return hotColor.equals(colors.hotColor) && coldColor.equals(colors.coldColor);
Objects.equals(x,y) > x.equals(y)

```suggestion
    return Objects.equals(hotColor, colors.hotColor) && Objects.equals(coldColor, colors.coldColor);
```

2022-03-22 19:01 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/Theme.java
> +  private float nodeSize  = 10.0f;
Hierfür sollte auch eine Konstante `DEFAULT_NODE_SIZE` angelegt werden.

2022-03-22 19:01 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/Theme.java
> +  public void setColdColor(Color coldColor) {
Falls hier noch JavaDoc hinzugefügt wird, würde ich hier definitiv noch erwähnen, dass die Methode hier auf die HeatmapColors zugreift und man den gleichen Effekt auch folgendermaßen erreichen kann:
```
theme.getHeatmapColors().setColdColor(color);
```

2022-03-22 19:01 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/jsonparsing/ColorSerializer.java
> +    gen.writeString("#" + addPrecedingZeroes(Integer.toHexString(value.hashCode())));
Die eigene Methode `addPrecedingZeros` ist überflüssig.
```suggestion
    gen.writeString("#" + value.hashCode().toString("X6"));
```

2022-03-22 19:01 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/config/GeneralConfigController.java
> +    if (theme != null) {
Hier sollte vermutlich sicherheitshalber noch überprüft werden, dass die einzelnen Colors nicht `null` sind
```suggestion
    if (theme != null && theme.getColdColor() != null && theme.getHotColor() != null) {
```

2022-03-22 19:30 UTC, quorty commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/HeatmapColors.java
> +    return hotColor.equals(colors.hotColor) && coldColor.equals(colors.coldColor);
Wurde angepasst.

2022-03-22 19:32 UTC, quorty commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/Theme.java
> +  private float nodeSize  = 10.0f;
gemacht, Boss!

2022-03-22 19:37 UTC, quorty commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/Theme.java
> +  public void setColdColor(Color coldColor) {
Habe das kommentiert.

2022-03-22 19:45 UTC, quorty commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/config/GeneralConfigController.java
> +    if (theme != null) {
Merci. J'ai fais ca.

2022-03-22 20:52 UTC, quorty commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/config/jsonparsing/ColorSerializer.java
> +    gen.writeString("#" + addPrecedingZeroes(Integer.toHexString(value.hashCode())));
Das war ein ziemlich guter Tipp denke ich.

2022-03-22 20:56 UTC, merged