Bugfix: ProcessedClausesSlider nun auch während eingehender Klauseln nutzbar
satviz/satviz pull request #56
Opened 2022-03-14 21:39 UTC by Tim-17

Hier wird das Problem gelöst, dass der Slider zum Vor- & Zurückspulen beim Visualisierungs-GUI nicht benutzbar war während gleichzeitig Klauseln reinkamen.
Außerdem wird hier der processedClausesSpinner angepasst, sodass er statt mit `int` nun mit `double` arbeitet (auch wenn es eigentlich `long` sein sollte -> Erklärung ist im Code gegeben).

2022-03-16 08:48 UTC, JohnnyJayJay requested changes
Muss noch mal einem Praxistest unterzogen werden, sonst gut.

2022-03-16 08:48 UTC, JohnnyJayJay commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/GuiUtils.java
> +        return object == null ? "" : df.format(object);
Da wir hier nur Ganzzahlen betrachten, kann man sich das DecimalFormat auch sparen und einfach direkt konvertieren.
```suggestion

      @Override
      public String toString(Double object) {
        return object == null ? "" : String.valueOf(object.longValue());
```

2022-03-17 21:59 UTC, Tim-17 commented on satviz-consumer/src/main/java/edu/kit/satviz/consumer/gui/GuiUtils.java
> +        return object == null ? "" : df.format(object);
Done.

2022-03-20 15:27 UTC, JohnnyJayJay approved these changes

2022-03-20 15:28 UTC, merged