Full coverage tests for satviz-sat module
satviz/satviz pull request #58
Opened 2022-03-15 23:25 UTC by quorty

98% Line Coverage (wäre 100% wenn's keinen unmöglichen default-case innerhalb einer Methode gäbe [könnte man evtl. beheben?]), 100% Method Coverage& 100% Class Coverage für das satviz-sat Modul.

2022-03-16 08:53 UTC, JohnnyJayJay requested changes
Gut, aber sowas wie toString sollte man nicht testen, selbst wenn es die Coverage erhöht.

2022-03-16 08:53 UTC, JohnnyJayJay commented on satviz-sat/src/test/java/edu/kit/satviz/sat/ClauseTest.java
> +  }
Würde ich tatsächlich rauslassen. toString hat kein festgeschriebenes Verhalten.

2022-03-16 08:53 UTC, JohnnyJayJay commented on satviz-sat/src/test/java/edu/kit/satviz/sat/SatAssignmentTest.java
> +  }
Siehe anderen Kommentar.

2022-03-16 09:23 UTC, quorty commented on satviz-sat/src/test/java/edu/kit/satviz/sat/ClauseTest.java
> +  }
wird gemacht.

2022-03-16 09:23 UTC, quorty commented on satviz-sat/src/test/java/edu/kit/satviz/sat/SatAssignmentTest.java
> +  }
Siehe Antwort auf anderen Kommentar.

2022-03-20 11:22 UTC, JohnnyJayJay approved these changes

2022-03-20 12:19 UTC, merged